# Generated by Django 4.0.3 on 2022-04-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='token',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
