# Generated by Django 4.0.3 on 2022-04-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='empresa',
        ),
    ]
