# Generated by Django 4.0.6 on 2022-07-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_estoquemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquemodel',
            name='validade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Validade do produto'),
        ),
    ]
