# Generated by Django 4.0.3 on 2022-04-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_usermodel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='token',
        ),
    ]
