# Generated by Django 4.0.3 on 2022-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_usermodel_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='token',
            field=models.BooleanField(default=False, verbose_name='Verificação do token'),
        ),
    ]
