# Generated by Django 4.0.3 on 2022-04-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_usermodel_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
