# Generated by Django 4.0.3 on 2022-03-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='senha2',
        ),
    ]
