# Generated by Django 4.0.3 on 2022-05-02 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_usermodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
