# Generated by Django 4.0.4 on 2022-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_usermodel_created_at_usermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
